FROM python:3.10-slim

WORKDIR /app

# Install dependencies with an upgraded pip and a longer timeout
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout=100 --no-cache-dir -r requirements.txt

# Copy the entire project code
COPY . .

# Streamlit's default port
EXPOSE 8501

# To Run Streamlit
CMD ["streamlit", "run", "fronend/frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]