FROM python:3.10-slim

WORKDIR /app

# Install dependencies with an upgraded pip and a longer timeout
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout=100 --no-cache-dir -r requirements.txt

# Copy the entire project code
COPY . .

# the backend port
EXPOSE 8000

# To Run Uvicorn
CMD ["uvicorn", "backend.newbackend:app", "--host", "0.0.0.0", "--port", "8000"]